name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t pavanimage .
  login:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - run: docker login 
      - run: ${{ secrtes.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
  push:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - run: docker tag pavanimage pavandocker143/dath
      - run: docker push pavandocker143/dath
      
